### ISSUE TITLE
There's no license info

### ISSUE THREAD

**Issue by berarma** [Foppygames/max-downforce#1]
Hi.

I've just found your game since it now has a Linux build. It's an awesome remake of an old classic that we all like. It's very nice.

The fact it doesn't have a license may limit its difussion. Have you thought about putting a license in your projects?

Without a license it must be considered a work with all rights reserved. That is, it's illegal to do anything with it without express consent from the author.

Using an open source license would help diffusion and it would also attract contributors. The GPL would ensure any derived work is still free for others. There are other opensource licenses that don't have this requirement but still would allow anyone to use your code and contribute.

Thanks.

**Comment by Foppygames** [comment]
Hi and thank you for your interest. I have added the GNU General Public License v3.0.

**Comment by Foppygames** [comment]
One point I would like to add is that the repository does not include the music files, because the license on the music requires that the files are not freely distributed. So I suppose this would mean that if someone makes their own game based on Max Downforce, they would have to add their own music. :)

**Comment by berarma** [comment]
That's great, thank you!

**Comment by leillo1975** [comment]
> One point I would like to add is that the repository does not include the music files, because the license on the music requires that the files are not freely distributed. So I suppose this would mean that if someone makes their own game based on Max Downforce, they would have to add their own music. :)

This is not a problem, you are only using this license on the source code you shared here

**Comment by JohnEBoyBaby** [comment]
Any MIT license possibilities for the community to grow branches from your seed, your fruit, your tree  young grasshopper ..? Just asking beCAUSE you know how 'dark' the 'darkness' can get out here and all ... sigh ... a lot of duplicative work too ... sigh again ... perhaps, if you wanted,  you know, you could just 'trust' 'us' of most PUREHEART in TRUTH to 'give' 'freely' and come Merry TRUTHmas time just somehow know a 'gift' is going to arrive ... can you 'feel' me coming through 'blessed' 'kind' beLOVEd one ..? Thank you. Respectfully, TRUTH
